# environment.yml

name: base
channels:
  - defaults
  - python=3.8
  - DevelopTool-Unified-Dev-Environment/
  - pandas
dependencies:
  - python=3.8
  - DevelopTool-Unified-Dev-Environment/
  - pandas
  - python=3.8
  - DevelopTool-Unified-Dev-Environment/
  - pandas
  - DevelopTool-Unified-Dev-Environment/
  - DevelopTool-Unified-Dev-Environment/
  - DevelopTool-Unified-Dev-Environment/
  - DevelopTool-Unified-Dev-Environment/
  - DevelopTool-Unified-Dev-Environment/
  - DevelopTool-Unified-Dev-Environment/
