name: Conda Environment Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Miniconda
        uses: conda-inc/setup-miniconda@v2

      - name: Install Conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda

      - name: Create Conda environment
        run: |
          conda env create --file ${{ github.workspace }}/DevelopTool-Unified-Dev-Environment/environment.yml --name base

      - name: Activate Conda environment
        run: conda activate base

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Generate coverage report
        run: coverage report

      - name: Run pylint
        run: pylint .

      - name: Clean up
        run: conda deactivate
          environment-name: base

      - name: Commit and Push Environment File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DevelopTool-Unified-Dev-Environment/environment.yml
          git commit -m "Update conda environment"
          git push
