name: Conda Environment Update

on:
  push:
    branches:
      - main

jobs:
  update_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Miniconda
        uses: conda-inc/setup-miniconda@v2

      - name: Update Conda Environment
        uses: conda-inc/conda-env-update@v1
        with:
          environment-file: DevelopTool-Unified-Dev-Environment/environment.yml
          environment-name: base

      - name: Commit and Push Environment File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DevelopTool-Unified-Dev-Environment/environment.yml
          git commit -m "Update conda environment"
          git push
