name: Conda Environment Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda

      - name: Create Conda environment
        run: |
          conda env create --file DevelopTool-Unified-Dev-Environment/environment.yml --name base

      - name: Commit and Push Environment File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DevelopTool-Unified-Dev-Environment/environment.yml
          git commit -m "Update conda environment"
          conda env remove --name base
